name: ServerPlugins
main: io.github.erich23.serverPlugins.ServerPlugins
version: 1.0
api-version: 1.16
commands:
   tp:
      description: Teleport players
      usage: /tp <teleport to> OR /tp <teleport from> <teleport to>
   gm:
      description: Change gamemode
      usage: /gm <s|c>
   home:
      description: teleport to over world home
      usage: /home